# Site settings
title: Marchel Revanza
smalltalk: "Personal Website"
description: > # Webnya Marchel Revanza
baseurl: "" # the subpath of your site, e.g. /blog/
paginate: 5
url: "" # the base hostname & protocol for your site
twitter_username: 
github_username:  
facebook_username: 
portfolio_url: 

# Build settings
markdown: kramdown
